using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace YTDM
{
    // UI text in the same ten languages as the browser extension. The app follows the Windows display
    // language unless one is picked in its window (Settings.Lang). Short on purpose: anything technical goes
    // to the log, not on screen. A key missing in a language falls back to English.
    static class S
    {
        // Language codes with their own names, in the order the extension lists them.
        public static readonly KeyValuePair<string, string>[] Languages =
        {
            new KeyValuePair<string, string>("en", "English"),
            new KeyValuePair<string, string>("de", "Deutsch"),
            new KeyValuePair<string, string>("es", "Español"),
            new KeyValuePair<string, string>("fr", "Français"),
            new KeyValuePair<string, string>("it", "Italiano"),
            new KeyValuePair<string, string>("pt", "Português"),
            new KeyValuePair<string, string>("pl", "Polski"),
            new KeyValuePair<string, string>("ru", "Русский"),
            new KeyValuePair<string, string>("ja", "日本語"),
            new KeyValuePair<string, string>("zh", "简体中文"),
        };

        static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            ["AppName"] = "YT Download Manager",
            ["Close"] = "Close",
            ["TryAgain"] = "Try again",
            ["Open"] = "Open",
            ["Change"] = "Change…",
            ["Allow"] = "Allow",
            ["Deny"] = "Don't allow",

            ["SetWindow"] = "YT Download Manager Setup",
            ["SetInstall"] = "Install",
            ["SetUpdate"] = "Update",
            ["SetInstalling"] = "Installing…",
            ["SetReady"] = "Ready.",
            ["SetFailed"] = "Couldn't install.",
            ["SetDetails"] = "Details",
            ["SetUpToDate"] = "Version {0} is installed and up to date.",
            ["SetCanUpdate"] = "Version {0} is installed. Update to {1}?",
            ["SetNewerInstalled"] = "A newer version ({0}) is installed.",
            ["SetRepair"] = "Repair",
            ["SetInstallVersion"] = "Install {0}",
            ["SetUninstall"] = "Uninstall",
            ["SetUpdating"] = "Updating…",
            ["SetRepairing"] = "Repairing…",
            ["SetUpdated"] = "Updated.",
            ["SetRepaired"] = "Repaired.",
            ["SetRemoveAsk"] = "Remove YT Download Manager? Your downloaded files stay where they are.",
            ["SetRemoving"] = "Removing…",
            ["SetRemoved"] = "Removed. Also remove the extension from your browser.",
            ["Cancel"] = "Cancel",

            ["HomeReady"] = "Ready",
            ["HomeActive"] = "Downloading · {0}",
            ["HomePreparing"] = "Getting ready…",
            ["HomePrepareFailed"] = "Couldn't get ready. Check your internet connection.",
            ["HomeSaving"] = "Saving to",
            ["HomeBrowser"] = "Browser",
            ["HomeConnected"] = "Connected",
            ["HomeNotConnected"] = "Not connected",
            ["HomeAdd"] = "Add to browser",
            ["HomeAddHint"] = "Turn on Developer mode, click Load unpacked, and paste. The folder path is copied.",
            ["HomeStartup"] = "Start with Windows",
            ["HomeLog"] = "Diagnostics",
            ["HomeSettings"] = "Settings",
            ["HomeLanguage"] = "Language",
            ["LangAuto"] = "Automatic",
            ["HomeVersion"] = "Version {0}",

            ["TrayActive"] = "YT Download Manager · downloading {0}",
            ["MnOpen"] = "Open",
            ["MnOpenFolder"] = "Open download folder",
            ["MnChangeFolder"] = "Change download folder…",
            ["MnExit"] = "Exit",
            ["ExitAsk"] = "Downloads are still running. They continue next time. Exit now?",
            ["ApiFail"] = "YT Download Manager couldn't start. Restart your PC and try again.",

            ["PairTitle"] = "Connect browser",
            ["PairAsk"] = "Let {0} save downloads through YT Download Manager?",
            ["PickFolder"] = "Choose a download folder",
            ["FolderMissing"] = "This folder isn't available.",
            ["FolderReadonly"] = "Files can't be saved here.",
            ["FolderBad"] = "This folder can't be used. Choose another one.",
            ["FolderGoneTitle"] = "Download folder not available",
            ["FolderGoneText"] = "{0} isn't available. Downloads wait until it's back.",

            ["UpdAvail"] = "Version {0} is available.",
            ["UpdNow"] = "Update",
            ["UpdMenu"] = "Update to version {0}",
            ["UpdLoading"] = "Downloading version {0}…",
            ["UpdFailed"] = "The update couldn't be downloaded.",
            ["UpdTitle"] = "Update available",
            ["UpdText"] = "Version {0} of YT Download Manager is ready. Click here to update.",
            ["UpdDoneTitle"] = "Updated",
            ["UpdDoneText"] = "YT Download Manager is now on version {0}.",

            ["UnAsk"] = "Remove YT Download Manager?\n\nYour downloaded files stay where they are.",
            ["UnDone"] = "YT Download Manager was removed.",
        };

        static readonly Dictionary<string, string> De = new Dictionary<string, string>
        {
            ["Close"] = "Schließen",
            ["TryAgain"] = "Erneut versuchen",
            ["Open"] = "Öffnen",
            ["Change"] = "Ändern…",
            ["Allow"] = "Zulassen",
            ["Deny"] = "Nicht zulassen",

            ["SetWindow"] = "YT Download Manager Setup",
            ["SetInstall"] = "Installieren",
            ["SetUpdate"] = "Aktualisieren",
            ["SetInstalling"] = "Wird installiert…",
            ["SetReady"] = "Bereit.",
            ["SetFailed"] = "Installation fehlgeschlagen.",
            ["SetDetails"] = "Details",
            ["SetUpToDate"] = "Version {0} ist installiert und aktuell.",
            ["SetCanUpdate"] = "Version {0} ist installiert. Auf {1} aktualisieren?",
            ["SetNewerInstalled"] = "Eine neuere Version ({0}) ist installiert.",
            ["SetRepair"] = "Reparieren",
            ["SetInstallVersion"] = "{0} installieren",
            ["SetUninstall"] = "Deinstallieren",
            ["SetUpdating"] = "Wird aktualisiert…",
            ["SetRepairing"] = "Wird repariert…",
            ["SetUpdated"] = "Aktualisiert.",
            ["SetRepaired"] = "Repariert.",
            ["SetRemoveAsk"] = "YT Download Manager entfernen? Deine heruntergeladenen Dateien bleiben erhalten.",
            ["SetRemoving"] = "Wird entfernt…",
            ["SetRemoved"] = "Entfernt. Entferne auch die Erweiterung aus deinem Browser.",
            ["Cancel"] = "Abbrechen",

            ["HomeReady"] = "Bereit",
            ["HomeActive"] = "Lädt herunter · {0}",
            ["HomePreparing"] = "Wird vorbereitet…",
            ["HomePrepareFailed"] = "Vorbereitung fehlgeschlagen. Prüfe deine Internetverbindung.",
            ["HomeSaving"] = "Speichern in",
            ["HomeBrowser"] = "Browser",
            ["HomeConnected"] = "Verbunden",
            ["HomeNotConnected"] = "Nicht verbunden",
            ["HomeAdd"] = "Zum Browser hinzufügen",
            ["HomeAddHint"] = "Entwicklermodus einschalten, „Entpackte Erweiterung laden“ klicken und einfügen. Der Ordnerpfad ist kopiert.",
            ["HomeStartup"] = "Mit Windows starten",
            ["HomeLog"] = "Diagnose",
            ["HomeSettings"] = "Einstellungen",
            ["HomeLanguage"] = "Sprache",
            ["LangAuto"] = "Automatisch",
            ["HomeVersion"] = "Version {0}",

            ["TrayActive"] = "YT Download Manager · lädt {0} herunter",
            ["MnOpen"] = "Öffnen",
            ["MnOpenFolder"] = "Download-Ordner öffnen",
            ["MnChangeFolder"] = "Download-Ordner ändern…",
            ["MnExit"] = "Beenden",
            ["ExitAsk"] = "Downloads laufen noch. Sie werden beim nächsten Mal fortgesetzt. Jetzt beenden?",
            ["ApiFail"] = "YT Download Manager konnte nicht starten. Starte den PC neu und versuche es noch einmal.",

            ["PairTitle"] = "Browser verbinden",
            ["PairAsk"] = "Darf {0} Downloads über YT Download Manager speichern?",
            ["PickFolder"] = "Download-Ordner wählen",
            ["FolderMissing"] = "Dieser Ordner ist nicht verfügbar.",
            ["FolderReadonly"] = "Hier können keine Dateien gespeichert werden.",
            ["FolderBad"] = "Dieser Ordner kann nicht verwendet werden. Wähle einen anderen.",
            ["FolderGoneTitle"] = "Download-Ordner nicht verfügbar",
            ["FolderGoneText"] = "{0} ist nicht verfügbar. Downloads warten, bis er wieder da ist.",

            ["UpdAvail"] = "Version {0} ist verfügbar.",
            ["UpdNow"] = "Aktualisieren",
            ["UpdMenu"] = "Auf Version {0} aktualisieren",
            ["UpdLoading"] = "Version {0} wird heruntergeladen…",
            ["UpdFailed"] = "Das Update konnte nicht heruntergeladen werden.",
            ["UpdTitle"] = "Update verfügbar",
            ["UpdText"] = "Version {0} von YT Download Manager ist bereit. Klicke hier zum Aktualisieren.",
            ["UpdDoneTitle"] = "Aktualisiert",
            ["UpdDoneText"] = "YT Download Manager ist jetzt auf Version {0}.",

            ["UnAsk"] = "YT Download Manager entfernen?\n\nDeine heruntergeladenen Dateien bleiben erhalten.",
            ["UnDone"] = "YT Download Manager wurde entfernt.",
        };

        static readonly Dictionary<string, string> Es = new Dictionary<string, string>
        {
            ["Close"] = "Cerrar",
            ["TryAgain"] = "Reintentar",
            ["Open"] = "Abrir",
            ["Change"] = "Cambiar…",
            ["Allow"] = "Permitir",
            ["Deny"] = "No permitir",

            ["SetWindow"] = "Instalación de YT Download Manager",
            ["SetInstall"] = "Instalar",
            ["SetUpdate"] = "Actualizar",
            ["SetInstalling"] = "Instalando…",
            ["SetReady"] = "Listo.",
            ["SetFailed"] = "No se pudo instalar.",
            ["SetDetails"] = "Detalles",
            ["SetUpToDate"] = "La versión {0} está instalada y al día.",
            ["SetCanUpdate"] = "La versión {0} está instalada. ¿Actualizar a la {1}?",
            ["SetNewerInstalled"] = "Hay instalada una versión más reciente ({0}).",
            ["SetRepair"] = "Reparar",
            ["SetInstallVersion"] = "Instalar la {0}",
            ["SetUninstall"] = "Desinstalar",
            ["SetUpdating"] = "Actualizando…",
            ["SetRepairing"] = "Reparando…",
            ["SetUpdated"] = "Actualizado.",
            ["SetRepaired"] = "Reparado.",
            ["SetRemoveAsk"] = "¿Quitar YT Download Manager? Tus archivos descargados se quedan donde están.",
            ["SetRemoving"] = "Quitando…",
            ["SetRemoved"] = "Quitado. Quita también la extensión de tu navegador.",
            ["Cancel"] = "Cancelar",

            ["HomeReady"] = "Listo",
            ["HomeActive"] = "Descargando · {0}",
            ["HomePreparing"] = "Preparando…",
            ["HomePrepareFailed"] = "No se pudo preparar. Comprueba tu conexión a internet.",
            ["HomeSaving"] = "Guardar en",
            ["HomeBrowser"] = "Navegador",
            ["HomeConnected"] = "Conectado",
            ["HomeNotConnected"] = "No conectado",
            ["HomeAdd"] = "Añadir al navegador",
            ["HomeAddHint"] = "Activa el modo de desarrollador, haz clic en «Cargar descomprimida» y pega. La ruta de la carpeta ya está copiada.",
            ["HomeStartup"] = "Iniciar con Windows",
            ["HomeLog"] = "Diagnóstico",
            ["HomeSettings"] = "Ajustes",
            ["HomeLanguage"] = "Idioma",
            ["LangAuto"] = "Automático",
            ["HomeVersion"] = "Versión {0}",

            ["TrayActive"] = "YT Download Manager · descargando {0}",
            ["MnOpen"] = "Abrir",
            ["MnOpenFolder"] = "Abrir carpeta de descargas",
            ["MnChangeFolder"] = "Cambiar carpeta de descargas…",
            ["MnExit"] = "Salir",
            ["ExitAsk"] = "Todavía hay descargas en curso. Seguirán la próxima vez. ¿Salir ahora?",
            ["ApiFail"] = "YT Download Manager no pudo iniciarse. Reinicia el PC e inténtalo de nuevo.",

            ["PairTitle"] = "Conectar navegador",
            ["PairAsk"] = "¿Permitir que {0} guarde descargas con YT Download Manager?",
            ["PickFolder"] = "Elige una carpeta de descargas",
            ["FolderMissing"] = "Esta carpeta no está disponible.",
            ["FolderReadonly"] = "Aquí no se pueden guardar archivos.",
            ["FolderBad"] = "Esta carpeta no se puede usar. Elige otra.",
            ["FolderGoneTitle"] = "Carpeta de descargas no disponible",
            ["FolderGoneText"] = "{0} no está disponible. Las descargas esperan hasta que vuelva.",

            ["UpdAvail"] = "La versión {0} está disponible.",
            ["UpdNow"] = "Actualizar",
            ["UpdMenu"] = "Actualizar a la versión {0}",
            ["UpdLoading"] = "Descargando la versión {0}…",
            ["UpdFailed"] = "No se pudo descargar la actualización.",
            ["UpdTitle"] = "Actualización disponible",
            ["UpdText"] = "La versión {0} de YT Download Manager está lista. Haz clic aquí para actualizar.",
            ["UpdDoneTitle"] = "Actualizado",
            ["UpdDoneText"] = "YT Download Manager ya está en la versión {0}.",

            ["UnAsk"] = "¿Quitar YT Download Manager?\n\nTus archivos descargados se quedan donde están.",
            ["UnDone"] = "Se quitó YT Download Manager.",
        };

        static readonly Dictionary<string, string> Fr = new Dictionary<string, string>
        {
            ["Close"] = "Fermer",
            ["TryAgain"] = "Réessayer",
            ["Open"] = "Ouvrir",
            ["Change"] = "Modifier…",
            ["Allow"] = "Autoriser",
            ["Deny"] = "Ne pas autoriser",

            ["SetWindow"] = "Installation de YT Download Manager",
            ["SetInstall"] = "Installer",
            ["SetUpdate"] = "Mettre à jour",
            ["SetInstalling"] = "Installation…",
            ["SetReady"] = "Prêt.",
            ["SetFailed"] = "Installation impossible.",
            ["SetDetails"] = "Détails",
            ["SetUpToDate"] = "La version {0} est installée et à jour.",
            ["SetCanUpdate"] = "La version {0} est installée. Passer à la {1} ?",
            ["SetNewerInstalled"] = "Une version plus récente ({0}) est installée.",
            ["SetRepair"] = "Réparer",
            ["SetInstallVersion"] = "Installer la {0}",
            ["SetUninstall"] = "Désinstaller",
            ["SetUpdating"] = "Mise à jour…",
            ["SetRepairing"] = "Réparation…",
            ["SetUpdated"] = "Mis à jour.",
            ["SetRepaired"] = "Réparé.",
            ["SetRemoveAsk"] = "Supprimer YT Download Manager ? Vos fichiers téléchargés restent où ils sont.",
            ["SetRemoving"] = "Suppression…",
            ["SetRemoved"] = "Supprimé. Retirez aussi l'extension de votre navigateur.",
            ["Cancel"] = "Annuler",

            ["HomeReady"] = "Prêt",
            ["HomeActive"] = "Téléchargement · {0}",
            ["HomePreparing"] = "Préparation…",
            ["HomePrepareFailed"] = "Préparation impossible. Vérifiez votre connexion internet.",
            ["HomeSaving"] = "Enregistrer dans",
            ["HomeBrowser"] = "Navigateur",
            ["HomeConnected"] = "Connecté",
            ["HomeNotConnected"] = "Non connecté",
            ["HomeAdd"] = "Ajouter au navigateur",
            ["HomeAddHint"] = "Activez le mode développeur, cliquez sur « Charger l'extension non empaquetée » et collez. Le chemin du dossier est copié.",
            ["HomeStartup"] = "Démarrer avec Windows",
            ["HomeLog"] = "Diagnostic",
            ["HomeSettings"] = "Paramètres",
            ["HomeLanguage"] = "Langue",
            ["LangAuto"] = "Automatique",
            ["HomeVersion"] = "Version {0}",

            ["TrayActive"] = "YT Download Manager · {0} en cours",
            ["MnOpen"] = "Ouvrir",
            ["MnOpenFolder"] = "Ouvrir le dossier de téléchargement",
            ["MnChangeFolder"] = "Changer de dossier de téléchargement…",
            ["MnExit"] = "Quitter",
            ["ExitAsk"] = "Des téléchargements sont en cours. Ils reprendront la prochaine fois. Quitter maintenant ?",
            ["ApiFail"] = "YT Download Manager n'a pas pu démarrer. Redémarrez le PC et réessayez.",

            ["PairTitle"] = "Connecter le navigateur",
            ["PairAsk"] = "Autoriser {0} à enregistrer des téléchargements avec YT Download Manager ?",
            ["PickFolder"] = "Choisissez un dossier de téléchargement",
            ["FolderMissing"] = "Ce dossier n'est pas disponible.",
            ["FolderReadonly"] = "Impossible d'enregistrer des fichiers ici.",
            ["FolderBad"] = "Ce dossier ne peut pas être utilisé. Choisissez-en un autre.",
            ["FolderGoneTitle"] = "Dossier de téléchargement indisponible",
            ["FolderGoneText"] = "{0} n'est pas disponible. Les téléchargements attendent son retour.",

            ["UpdAvail"] = "La version {0} est disponible.",
            ["UpdNow"] = "Mettre à jour",
            ["UpdMenu"] = "Passer à la version {0}",
            ["UpdLoading"] = "Téléchargement de la version {0}…",
            ["UpdFailed"] = "La mise à jour n'a pas pu être téléchargée.",
            ["UpdTitle"] = "Mise à jour disponible",
            ["UpdText"] = "La version {0} de YT Download Manager est prête. Cliquez ici pour mettre à jour.",
            ["UpdDoneTitle"] = "Mis à jour",
            ["UpdDoneText"] = "YT Download Manager est maintenant en version {0}.",

            ["UnAsk"] = "Supprimer YT Download Manager ?\n\nVos fichiers téléchargés restent où ils sont.",
            ["UnDone"] = "YT Download Manager a été supprimé.",
        };

        static readonly Dictionary<string, string> It = new Dictionary<string, string>
        {
            ["Close"] = "Chiudi",
            ["TryAgain"] = "Riprova",
            ["Open"] = "Apri",
            ["Change"] = "Cambia…",
            ["Allow"] = "Consenti",
            ["Deny"] = "Non consentire",

            ["SetWindow"] = "Installazione di YT Download Manager",
            ["SetInstall"] = "Installa",
            ["SetUpdate"] = "Aggiorna",
            ["SetInstalling"] = "Installazione in corso…",
            ["SetReady"] = "Pronto.",
            ["SetFailed"] = "Installazione non riuscita.",
            ["SetDetails"] = "Dettagli",
            ["SetUpToDate"] = "La versione {0} è installata e aggiornata.",
            ["SetCanUpdate"] = "È installata la versione {0}. Aggiornare alla {1}?",
            ["SetNewerInstalled"] = "È installata una versione più recente ({0}).",
            ["SetRepair"] = "Ripara",
            ["SetInstallVersion"] = "Installa la {0}",
            ["SetUninstall"] = "Disinstalla",
            ["SetUpdating"] = "Aggiornamento in corso…",
            ["SetRepairing"] = "Riparazione in corso…",
            ["SetUpdated"] = "Aggiornato.",
            ["SetRepaired"] = "Riparato.",
            ["SetRemoveAsk"] = "Rimuovere YT Download Manager? I file scaricati restano dove sono.",
            ["SetRemoving"] = "Rimozione in corso…",
            ["SetRemoved"] = "Rimosso. Rimuovi anche l'estensione dal browser.",
            ["Cancel"] = "Annulla",

            ["HomeReady"] = "Pronto",
            ["HomeActive"] = "Download in corso · {0}",
            ["HomePreparing"] = "Preparazione…",
            ["HomePrepareFailed"] = "Preparazione non riuscita. Controlla la connessione a internet.",
            ["HomeSaving"] = "Salva in",
            ["HomeBrowser"] = "Browser",
            ["HomeConnected"] = "Connesso",
            ["HomeNotConnected"] = "Non connesso",
            ["HomeAdd"] = "Aggiungi al browser",
            ["HomeAddHint"] = "Attiva la modalità sviluppatore, fai clic su «Carica estensione non pacchettizzata» e incolla. Il percorso della cartella è già copiato.",
            ["HomeStartup"] = "Avvia con Windows",
            ["HomeLog"] = "Diagnostica",
            ["HomeSettings"] = "Impostazioni",
            ["HomeLanguage"] = "Lingua",
            ["LangAuto"] = "Automatica",
            ["HomeVersion"] = "Versione {0}",

            ["TrayActive"] = "YT Download Manager · {0} in download",
            ["MnOpen"] = "Apri",
            ["MnOpenFolder"] = "Apri cartella download",
            ["MnChangeFolder"] = "Cambia cartella download…",
            ["MnExit"] = "Esci",
            ["ExitAsk"] = "Ci sono download in corso. Riprenderanno la prossima volta. Uscire ora?",
            ["ApiFail"] = "Impossibile avviare YT Download Manager. Riavvia il PC e riprova.",

            ["PairTitle"] = "Connetti browser",
            ["PairAsk"] = "Consentire a {0} di salvare i download tramite YT Download Manager?",
            ["PickFolder"] = "Scegli una cartella per i download",
            ["FolderMissing"] = "Questa cartella non è disponibile.",
            ["FolderReadonly"] = "Qui non è possibile salvare file.",
            ["FolderBad"] = "Questa cartella non può essere usata. Scegline un'altra.",
            ["FolderGoneTitle"] = "Cartella download non disponibile",
            ["FolderGoneText"] = "{0} non è disponibile. I download attendono che torni.",

            ["UpdAvail"] = "È disponibile la versione {0}.",
            ["UpdNow"] = "Aggiorna",
            ["UpdMenu"] = "Aggiorna alla versione {0}",
            ["UpdLoading"] = "Download della versione {0}…",
            ["UpdFailed"] = "Impossibile scaricare l'aggiornamento.",
            ["UpdTitle"] = "Aggiornamento disponibile",
            ["UpdText"] = "La versione {0} di YT Download Manager è pronta. Fai clic qui per aggiornare.",
            ["UpdDoneTitle"] = "Aggiornato",
            ["UpdDoneText"] = "YT Download Manager ora è alla versione {0}.",

            ["UnAsk"] = "Rimuovere YT Download Manager?\n\nI file scaricati restano dove sono.",
            ["UnDone"] = "YT Download Manager è stato rimosso.",
        };

        static readonly Dictionary<string, string> Pt = new Dictionary<string, string>
        {
            ["Close"] = "Fechar",
            ["TryAgain"] = "Tentar novamente",
            ["Open"] = "Abrir",
            ["Change"] = "Alterar…",
            ["Allow"] = "Permitir",
            ["Deny"] = "Não permitir",

            ["SetWindow"] = "Instalação do YT Download Manager",
            ["SetInstall"] = "Instalar",
            ["SetUpdate"] = "Atualizar",
            ["SetInstalling"] = "Instalando…",
            ["SetReady"] = "Pronto.",
            ["SetFailed"] = "Não foi possível instalar.",
            ["SetDetails"] = "Detalhes",
            ["SetUpToDate"] = "A versão {0} está instalada e atualizada.",
            ["SetCanUpdate"] = "A versão {0} está instalada. Atualizar para a {1}?",
            ["SetNewerInstalled"] = "Uma versão mais recente ({0}) está instalada.",
            ["SetRepair"] = "Reparar",
            ["SetInstallVersion"] = "Instalar a {0}",
            ["SetUninstall"] = "Desinstalar",
            ["SetUpdating"] = "Atualizando…",
            ["SetRepairing"] = "Reparando…",
            ["SetUpdated"] = "Atualizado.",
            ["SetRepaired"] = "Reparado.",
            ["SetRemoveAsk"] = "Remover o YT Download Manager? Seus arquivos baixados continuam onde estão.",
            ["SetRemoving"] = "Removendo…",
            ["SetRemoved"] = "Removido. Remova também a extensão do navegador.",
            ["Cancel"] = "Cancelar",

            ["HomeReady"] = "Pronto",
            ["HomeActive"] = "Baixando · {0}",
            ["HomePreparing"] = "Preparando…",
            ["HomePrepareFailed"] = "Não foi possível preparar. Verifique sua conexão com a internet.",
            ["HomeSaving"] = "Salvar em",
            ["HomeBrowser"] = "Navegador",
            ["HomeConnected"] = "Conectado",
            ["HomeNotConnected"] = "Não conectado",
            ["HomeAdd"] = "Adicionar ao navegador",
            ["HomeAddHint"] = "Ative o Modo do desenvolvedor, clique em \"Carregar sem compactação\" e cole. O caminho da pasta já foi copiado.",
            ["HomeStartup"] = "Iniciar com o Windows",
            ["HomeLog"] = "Diagnóstico",
            ["HomeSettings"] = "Configurações",
            ["HomeLanguage"] = "Idioma",
            ["LangAuto"] = "Automático",
            ["HomeVersion"] = "Versão {0}",

            ["TrayActive"] = "YT Download Manager · baixando {0}",
            ["MnOpen"] = "Abrir",
            ["MnOpenFolder"] = "Abrir pasta de downloads",
            ["MnChangeFolder"] = "Alterar pasta de downloads…",
            ["MnExit"] = "Sair",
            ["ExitAsk"] = "Ainda há downloads em andamento. Eles continuam na próxima vez. Sair agora?",
            ["ApiFail"] = "Não foi possível iniciar o YT Download Manager. Reinicie o PC e tente novamente.",

            ["PairTitle"] = "Conectar navegador",
            ["PairAsk"] = "Permitir que {0} salve downloads pelo YT Download Manager?",
            ["PickFolder"] = "Escolha uma pasta de downloads",
            ["FolderMissing"] = "Esta pasta não está disponível.",
            ["FolderReadonly"] = "Não é possível salvar arquivos aqui.",
            ["FolderBad"] = "Esta pasta não pode ser usada. Escolha outra.",
            ["FolderGoneTitle"] = "Pasta de downloads indisponível",
            ["FolderGoneText"] = "{0} não está disponível. Os downloads aguardam até ela voltar.",

            ["UpdAvail"] = "A versão {0} está disponível.",
            ["UpdNow"] = "Atualizar",
            ["UpdMenu"] = "Atualizar para a versão {0}",
            ["UpdLoading"] = "Baixando a versão {0}…",
            ["UpdFailed"] = "Não foi possível baixar a atualização.",
            ["UpdTitle"] = "Atualização disponível",
            ["UpdText"] = "A versão {0} do YT Download Manager está pronta. Clique aqui para atualizar.",
            ["UpdDoneTitle"] = "Atualizado",
            ["UpdDoneText"] = "O YT Download Manager agora está na versão {0}.",

            ["UnAsk"] = "Remover o YT Download Manager?\n\nSeus arquivos baixados continuam onde estão.",
            ["UnDone"] = "O YT Download Manager foi removido.",
        };

        static readonly Dictionary<string, string> Pl = new Dictionary<string, string>
        {
            ["Close"] = "Zamknij",
            ["TryAgain"] = "Spróbuj ponownie",
            ["Open"] = "Otwórz",
            ["Change"] = "Zmień…",
            ["Allow"] = "Zezwól",
            ["Deny"] = "Nie zezwalaj",

            ["SetWindow"] = "Instalator YT Download Manager",
            ["SetInstall"] = "Zainstaluj",
            ["SetUpdate"] = "Aktualizuj",
            ["SetInstalling"] = "Instalowanie…",
            ["SetReady"] = "Gotowe.",
            ["SetFailed"] = "Nie udało się zainstalować.",
            ["SetDetails"] = "Szczegóły",
            ["SetUpToDate"] = "Zainstalowana wersja {0} jest aktualna.",
            ["SetCanUpdate"] = "Zainstalowana jest wersja {0}. Zaktualizować do {1}?",
            ["SetNewerInstalled"] = "Zainstalowana jest nowsza wersja ({0}).",
            ["SetRepair"] = "Napraw",
            ["SetInstallVersion"] = "Zainstaluj {0}",
            ["SetUninstall"] = "Odinstaluj",
            ["SetUpdating"] = "Aktualizowanie…",
            ["SetRepairing"] = "Naprawianie…",
            ["SetUpdated"] = "Zaktualizowano.",
            ["SetRepaired"] = "Naprawiono.",
            ["SetRemoveAsk"] = "Usunąć YT Download Manager? Pobrane pliki pozostaną na miejscu.",
            ["SetRemoving"] = "Usuwanie…",
            ["SetRemoved"] = "Usunięto. Usuń też rozszerzenie z przeglądarki.",
            ["Cancel"] = "Anuluj",

            ["HomeReady"] = "Gotowe",
            ["HomeActive"] = "Pobieranie · {0}",
            ["HomePreparing"] = "Przygotowywanie…",
            ["HomePrepareFailed"] = "Nie udało się przygotować. Sprawdź połączenie z internetem.",
            ["HomeSaving"] = "Zapisuj w",
            ["HomeBrowser"] = "Przeglądarka",
            ["HomeConnected"] = "Połączono",
            ["HomeNotConnected"] = "Nie połączono",
            ["HomeAdd"] = "Dodaj do przeglądarki",
            ["HomeAddHint"] = "Włącz tryb dewelopera, kliknij „Załaduj rozpakowane” i wklej. Ścieżka folderu jest już skopiowana.",
            ["HomeStartup"] = "Uruchamiaj z systemem Windows",
            ["HomeLog"] = "Diagnostyka",
            ["HomeSettings"] = "Ustawienia",
            ["HomeLanguage"] = "Język",
            ["LangAuto"] = "Automatycznie",
            ["HomeVersion"] = "Wersja {0}",

            ["TrayActive"] = "YT Download Manager · pobieranie: {0}",
            ["MnOpen"] = "Otwórz",
            ["MnOpenFolder"] = "Otwórz folder pobranych",
            ["MnChangeFolder"] = "Zmień folder pobranych…",
            ["MnExit"] = "Zakończ",
            ["ExitAsk"] = "Pobieranie wciąż trwa. Zostanie wznowione następnym razem. Zakończyć teraz?",
            ["ApiFail"] = "Nie udało się uruchomić YT Download Manager. Uruchom ponownie komputer i spróbuj jeszcze raz.",

            ["PairTitle"] = "Połącz przeglądarkę",
            ["PairAsk"] = "Zezwolić {0} na zapisywanie pobranych plików przez YT Download Manager?",
            ["PickFolder"] = "Wybierz folder pobranych",
            ["FolderMissing"] = "Ten folder jest niedostępny.",
            ["FolderReadonly"] = "Nie można tu zapisywać plików.",
            ["FolderBad"] = "Nie można użyć tego folderu. Wybierz inny.",
            ["FolderGoneTitle"] = "Folder pobranych jest niedostępny",
            ["FolderGoneText"] = "{0} jest niedostępny. Pobieranie poczeka, aż wróci.",

            ["UpdAvail"] = "Dostępna jest wersja {0}.",
            ["UpdNow"] = "Aktualizuj",
            ["UpdMenu"] = "Aktualizuj do wersji {0}",
            ["UpdLoading"] = "Pobieranie wersji {0}…",
            ["UpdFailed"] = "Nie udało się pobrać aktualizacji.",
            ["UpdTitle"] = "Dostępna aktualizacja",
            ["UpdText"] = "Wersja {0} YT Download Manager jest gotowa. Kliknij tutaj, aby zaktualizować.",
            ["UpdDoneTitle"] = "Zaktualizowano",
            ["UpdDoneText"] = "YT Download Manager ma teraz wersję {0}.",

            ["UnAsk"] = "Usunąć YT Download Manager?\n\nPobrane pliki pozostaną na miejscu.",
            ["UnDone"] = "YT Download Manager został usunięty.",
        };

        static readonly Dictionary<string, string> Ru = new Dictionary<string, string>
        {
            ["Close"] = "Закрыть",
            ["TryAgain"] = "Повторить",
            ["Open"] = "Открыть",
            ["Change"] = "Изменить…",
            ["Allow"] = "Разрешить",
            ["Deny"] = "Не разрешать",

            ["SetWindow"] = "Установка YT Download Manager",
            ["SetInstall"] = "Установить",
            ["SetUpdate"] = "Обновить",
            ["SetInstalling"] = "Установка…",
            ["SetReady"] = "Готово.",
            ["SetFailed"] = "Не удалось установить.",
            ["SetDetails"] = "Подробнее",
            ["SetUpToDate"] = "Установлена актуальная версия {0}.",
            ["SetCanUpdate"] = "Установлена версия {0}. Обновить до {1}?",
            ["SetNewerInstalled"] = "Установлена более новая версия ({0}).",
            ["SetRepair"] = "Восстановить",
            ["SetInstallVersion"] = "Установить {0}",
            ["SetUninstall"] = "Удалить",
            ["SetUpdating"] = "Обновление…",
            ["SetRepairing"] = "Восстановление…",
            ["SetUpdated"] = "Обновлено.",
            ["SetRepaired"] = "Восстановлено.",
            ["SetRemoveAsk"] = "Удалить YT Download Manager? Скачанные файлы останутся на месте.",
            ["SetRemoving"] = "Удаление…",
            ["SetRemoved"] = "Удалено. Удалите также расширение из браузера.",
            ["Cancel"] = "Отмена",

            ["HomeReady"] = "Готово",
            ["HomeActive"] = "Загрузка · {0}",
            ["HomePreparing"] = "Подготовка…",
            ["HomePrepareFailed"] = "Не удалось подготовиться. Проверьте подключение к интернету.",
            ["HomeSaving"] = "Сохранять в",
            ["HomeBrowser"] = "Браузер",
            ["HomeConnected"] = "Подключено",
            ["HomeNotConnected"] = "Не подключено",
            ["HomeAdd"] = "Добавить в браузер",
            ["HomeAddHint"] = "Включите «Режим разработчика», нажмите «Загрузить распакованное расширение» и вставьте путь. Путь к папке уже скопирован.",
            ["HomeStartup"] = "Запускать вместе с Windows",
            ["HomeLog"] = "Диагностика",
            ["HomeSettings"] = "Настройки",
            ["HomeLanguage"] = "Язык",
            ["LangAuto"] = "Автоматически",
            ["HomeVersion"] = "Версия {0}",

            ["TrayActive"] = "YT Download Manager · загрузок: {0}",
            ["MnOpen"] = "Открыть",
            ["MnOpenFolder"] = "Открыть папку загрузок",
            ["MnChangeFolder"] = "Изменить папку загрузок…",
            ["MnExit"] = "Выход",
            ["ExitAsk"] = "Загрузки ещё идут. Они продолжатся в следующий раз. Выйти сейчас?",
            ["ApiFail"] = "Не удалось запустить YT Download Manager. Перезагрузите компьютер и попробуйте снова.",

            ["PairTitle"] = "Подключить браузер",
            ["PairAsk"] = "Разрешить {0} сохранять загрузки через YT Download Manager?",
            ["PickFolder"] = "Выберите папку для загрузок",
            ["FolderMissing"] = "Эта папка недоступна.",
            ["FolderReadonly"] = "Здесь нельзя сохранять файлы.",
            ["FolderBad"] = "Эту папку нельзя использовать. Выберите другую.",
            ["FolderGoneTitle"] = "Папка загрузок недоступна",
            ["FolderGoneText"] = "{0} недоступна. Загрузки подождут, пока она не появится.",

            ["UpdAvail"] = "Доступна версия {0}.",
            ["UpdNow"] = "Обновить",
            ["UpdMenu"] = "Обновить до версии {0}",
            ["UpdLoading"] = "Загрузка версии {0}…",
            ["UpdFailed"] = "Не удалось загрузить обновление.",
            ["UpdTitle"] = "Доступно обновление",
            ["UpdText"] = "Версия {0} YT Download Manager готова. Нажмите здесь, чтобы обновить.",
            ["UpdDoneTitle"] = "Обновлено",
            ["UpdDoneText"] = "YT Download Manager обновлён до версии {0}.",

            ["UnAsk"] = "Удалить YT Download Manager?\n\nСкачанные файлы останутся на месте.",
            ["UnDone"] = "YT Download Manager удалён.",
        };

        static readonly Dictionary<string, string> Ja = new Dictionary<string, string>
        {
            ["Close"] = "閉じる",
            ["TryAgain"] = "再試行",
            ["Open"] = "開く",
            ["Change"] = "変更…",
            ["Allow"] = "許可",
            ["Deny"] = "許可しない",

            ["SetWindow"] = "YT Download Manager セットアップ",
            ["SetInstall"] = "インストール",
            ["SetUpdate"] = "更新",
            ["SetInstalling"] = "インストール中…",
            ["SetReady"] = "完了しました。",
            ["SetFailed"] = "インストールできませんでした。",
            ["SetDetails"] = "詳細",
            ["SetUpToDate"] = "バージョン {0} がインストールされていて、最新です。",
            ["SetCanUpdate"] = "バージョン {0} がインストールされています。{1} に更新しますか?",
            ["SetNewerInstalled"] = "新しいバージョン ({0}) がインストールされています。",
            ["SetRepair"] = "修復",
            ["SetInstallVersion"] = "{0} をインストール",
            ["SetUninstall"] = "アンインストール",
            ["SetUpdating"] = "更新中…",
            ["SetRepairing"] = "修復中…",
            ["SetUpdated"] = "更新しました。",
            ["SetRepaired"] = "修復しました。",
            ["SetRemoveAsk"] = "YT Download Manager を削除しますか? ダウンロードしたファイルはそのまま残ります。",
            ["SetRemoving"] = "削除中…",
            ["SetRemoved"] = "削除しました。ブラウザーから拡張機能も削除してください。",
            ["Cancel"] = "キャンセル",

            ["HomeReady"] = "準備完了",
            ["HomeActive"] = "ダウンロード中 · {0}",
            ["HomePreparing"] = "準備中…",
            ["HomePrepareFailed"] = "準備できませんでした。インターネット接続を確認してください。",
            ["HomeSaving"] = "保存先",
            ["HomeBrowser"] = "ブラウザー",
            ["HomeConnected"] = "接続済み",
            ["HomeNotConnected"] = "未接続",
            ["HomeAdd"] = "ブラウザーに追加",
            ["HomeAddHint"] = "「デベロッパー モード」をオンにし、「パッケージ化されていない拡張機能を読み込む」をクリックして貼り付けます。フォルダーのパスはコピー済みです。",
            ["HomeStartup"] = "Windows の起動時に開始",
            ["HomeLog"] = "診断",
            ["HomeSettings"] = "設定",
            ["HomeLanguage"] = "言語",
            ["LangAuto"] = "自動",
            ["HomeVersion"] = "バージョン {0}",

            ["TrayActive"] = "YT Download Manager · {0} 件ダウンロード中",
            ["MnOpen"] = "開く",
            ["MnOpenFolder"] = "ダウンロード フォルダーを開く",
            ["MnChangeFolder"] = "ダウンロード フォルダーを変更…",
            ["MnExit"] = "終了",
            ["ExitAsk"] = "ダウンロードがまだ実行中です。次回、続きから再開します。今すぐ終了しますか?",
            ["ApiFail"] = "YT Download Manager を起動できませんでした。PC を再起動して、もう一度お試しください。",

            ["PairTitle"] = "ブラウザーを接続",
            ["PairAsk"] = "{0} が YT Download Manager でダウンロードを保存することを許可しますか?",
            ["PickFolder"] = "ダウンロード フォルダーを選択",
            ["FolderMissing"] = "このフォルダーは利用できません。",
            ["FolderReadonly"] = "ここにはファイルを保存できません。",
            ["FolderBad"] = "このフォルダーは使用できません。別のフォルダーを選んでください。",
            ["FolderGoneTitle"] = "ダウンロード フォルダーを利用できません",
            ["FolderGoneText"] = "{0} を利用できません。戻るまでダウンロードは待機します。",

            ["UpdAvail"] = "バージョン {0} を利用できます。",
            ["UpdNow"] = "更新",
            ["UpdMenu"] = "バージョン {0} に更新",
            ["UpdLoading"] = "バージョン {0} をダウンロード中…",
            ["UpdFailed"] = "更新をダウンロードできませんでした。",
            ["UpdTitle"] = "更新があります",
            ["UpdText"] = "YT Download Manager のバージョン {0} の準備ができました。ここをクリックして更新します。",
            ["UpdDoneTitle"] = "更新しました",
            ["UpdDoneText"] = "YT Download Manager はバージョン {0} になりました。",

            ["UnAsk"] = "YT Download Manager を削除しますか?\n\nダウンロードしたファイルはそのまま残ります。",
            ["UnDone"] = "YT Download Manager を削除しました。",
        };

        static readonly Dictionary<string, string> Zh = new Dictionary<string, string>
        {
            ["Close"] = "关闭",
            ["TryAgain"] = "重试",
            ["Open"] = "打开",
            ["Change"] = "更改…",
            ["Allow"] = "允许",
            ["Deny"] = "不允许",

            ["SetWindow"] = "YT Download Manager 安装程序",
            ["SetInstall"] = "安装",
            ["SetUpdate"] = "更新",
            ["SetInstalling"] = "正在安装…",
            ["SetReady"] = "已完成。",
            ["SetFailed"] = "无法安装。",
            ["SetDetails"] = "详细信息",
            ["SetUpToDate"] = "已安装版本 {0}，已是最新版本。",
            ["SetCanUpdate"] = "已安装版本 {0}。要更新到 {1} 吗？",
            ["SetNewerInstalled"] = "已安装更新的版本 ({0})。",
            ["SetRepair"] = "修复",
            ["SetInstallVersion"] = "安装 {0}",
            ["SetUninstall"] = "卸载",
            ["SetUpdating"] = "正在更新…",
            ["SetRepairing"] = "正在修复…",
            ["SetUpdated"] = "已更新。",
            ["SetRepaired"] = "已修复。",
            ["SetRemoveAsk"] = "要删除 YT Download Manager 吗？已下载的文件会保留在原处。",
            ["SetRemoving"] = "正在删除…",
            ["SetRemoved"] = "已删除。请同时从浏览器中移除扩展程序。",
            ["Cancel"] = "取消",

            ["HomeReady"] = "就绪",
            ["HomeActive"] = "正在下载 · {0}",
            ["HomePreparing"] = "正在准备…",
            ["HomePrepareFailed"] = "准备失败。请检查网络连接。",
            ["HomeSaving"] = "保存到",
            ["HomeBrowser"] = "浏览器",
            ["HomeConnected"] = "已连接",
            ["HomeNotConnected"] = "未连接",
            ["HomeAdd"] = "添加到浏览器",
            ["HomeAddHint"] = "打开“开发者模式”，点击“加载已解压的扩展程序”，然后粘贴。文件夹路径已复制。",
            ["HomeStartup"] = "随 Windows 启动",
            ["HomeLog"] = "诊断",
            ["HomeSettings"] = "设置",
            ["HomeLanguage"] = "语言",
            ["LangAuto"] = "自动",
            ["HomeVersion"] = "版本 {0}",

            ["TrayActive"] = "YT Download Manager · 正在下载 {0} 个",
            ["MnOpen"] = "打开",
            ["MnOpenFolder"] = "打开下载文件夹",
            ["MnChangeFolder"] = "更改下载文件夹…",
            ["MnExit"] = "退出",
            ["ExitAsk"] = "仍有下载正在进行，下次会继续。现在退出吗？",
            ["ApiFail"] = "无法启动 YT Download Manager。请重启电脑后重试。",

            ["PairTitle"] = "连接浏览器",
            ["PairAsk"] = "允许 {0} 通过 YT Download Manager 保存下载内容吗？",
            ["PickFolder"] = "选择下载文件夹",
            ["FolderMissing"] = "此文件夹不可用。",
            ["FolderReadonly"] = "无法在此处保存文件。",
            ["FolderBad"] = "无法使用此文件夹，请选择其他文件夹。",
            ["FolderGoneTitle"] = "下载文件夹不可用",
            ["FolderGoneText"] = "{0} 不可用。下载会等待它恢复。",

            ["UpdAvail"] = "版本 {0} 已可用。",
            ["UpdNow"] = "更新",
            ["UpdMenu"] = "更新到版本 {0}",
            ["UpdLoading"] = "正在下载版本 {0}…",
            ["UpdFailed"] = "无法下载更新。",
            ["UpdTitle"] = "有可用更新",
            ["UpdText"] = "YT Download Manager 版本 {0} 已就绪。点击此处更新。",
            ["UpdDoneTitle"] = "已更新",
            ["UpdDoneText"] = "YT Download Manager 已更新到版本 {0}。",

            ["UnAsk"] = "要删除 YT Download Manager 吗？\n\n已下载的文件会保留在原处。",
            ["UnDone"] = "已删除 YT Download Manager。",
        };

        static readonly Dictionary<string, Dictionary<string, string>> All = new Dictionary<string, Dictionary<string, string>>
        {
            ["en"] = En, ["de"] = De, ["es"] = Es, ["fr"] = Fr, ["it"] = It,
            ["pt"] = Pt, ["pl"] = Pl, ["ru"] = Ru, ["ja"] = Ja, ["zh"] = Zh,
        };

        // Windows' display language when the app has it, otherwise English.
        public static string SystemLang
        {
            get
            {
                var two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
                return All.ContainsKey(two) ? two : "en";
            }
        }

        // The language in use: the one picked in the app's window, or Windows' own.
        public static string Lang
        {
            get
            {
                var picked = Settings.Current?.Lang;
                return picked != null && All.ContainsKey(picked) ? picked : SystemLang;
            }
        }

        public static string Name(string code) => Languages.FirstOrDefault(l => l.Key == code).Value ?? code;

        public static string T(string key) => All[Lang].TryGetValue(key, out var v) ? v : En.TryGetValue(key, out var e) ? e : key;
        public static string T(string key, params object[] args) => string.Format(T(key), args);
    }
}
